name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main # Change to your main branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: package Code  
        run:  zip -r deploy.zip ./

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}                                                                                               
          application_name: ebs-actions
          environment_name: Ebs-actions-env
          existing_bucket_name: elasticbeanstalk-ap-south-1-162105714209
          region: ap-south-1 # Modify to match your desired region    
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
